// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingCleanArchitecture.InfrastructureLayer.Data;

#nullable disable

namespace TicketingCleanArchitecture.InfrastructureLayer.Migration
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240710103742_DropTableAnswerTicket")]
    partial class DropTableAnswerTicket
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnswerTicket", b =>
                {
                    b.Property<int>("AnswersId")
                        .HasColumnType("int");

                    b.Property<int>("RepliesId")
                        .HasColumnType("int");

                    b.HasKey("AnswersId", "RepliesId");

                    b.HasIndex("RepliesId");

                    b.ToTable("AnswerTicket");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupportTeamMemberID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SupportTeamMemberID");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.SupportTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("SupportTeamMembers");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.TicketAnswer", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("TicketAnswer");
                });

            modelBuilder.Entity("AnswerTicket", b =>
                {
                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.Answer", null)
                        .WithMany()
                        .HasForeignKey("AnswersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("RepliesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Answer", b =>
                {
                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.SupportTeamMember", "SupportTeamMember")
                        .WithMany("Answers")
                        .HasForeignKey("SupportTeamMemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTeamMember");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Ticket", b =>
                {
                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.TicketAnswer", b =>
                {
                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.Answer", "Answer")
                        .WithMany("TicketAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingCleanArchitecture.CoreLayer.Entities.Ticket", "Ticket")
                        .WithMany("TicketAnswers")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Answer", b =>
                {
                    b.Navigation("TicketAnswers");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.SupportTeamMember", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("TicketingCleanArchitecture.CoreLayer.Entities.Ticket", b =>
                {
                    b.Navigation("TicketAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
